version: "3"
services:
  db:
    container_name: h2-db
    image: oscarfonts/h2:1.4.199
    ports:
      - "1521:1521"
      - "8081:81"
    volumes:
      - /Users/kjh/docker/h2_docker/test:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists
    restart: always
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring-board
    ports:
      - "8080:8080"
    command: ["java", "-jar", "boongboard-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
    restart: always

